// Stage 3 of welcome -> chat -> document: the finished requirements
// document. Same data and same actions as before (download, refine, start
// over) - restyled into the mockup's document layout: a table-of-contents
// sidebar, all 5 sections stacked in one scrollable column, and a Refine
// chat panel on the right.
import RefinePanel from "./RefinePanel";
import {
  RequirementsSection,
  UserStoriesSection,
  AcceptanceCriteriaSection,
  UseCasesSection,
  AssumptionsSection,
} from "./DocumentSections";

const TOC = [
  { num: "1", label: "Requirements", id: "sec-1" },
  { num: "2", label: "User Stories", id: "sec-2" },
  { num: "3", label: "Acceptance Criteria", id: "sec-3" },
  { num: "4", label: "Use Cases", id: "sec-4" },
  { num: "5", label: "Assumptions", id: "sec-5" },
];

function scrollToSection(id) {
  document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
}

export default function DocumentStage({
  data,
  onDownload,
  downloading,
  onStartOver,
  onBackToChat,
  onRefine,
  refineHistory,
  refining,
  refineError,
}) {
  const useCases = data.use_cases || [];
  const assumptions = data.assumptions || [];

  return (
    <div className="h-screen flex flex-col">
      <header className="h-16 flex-none flex items-center justify-between gap-4 px-6 bg-white border-b border-border">
        <div className="flex items-center gap-2.5 flex-none">
          <div className="font-display font-extrabold text-lg tracking-tight">ReqPrint</div>
        </div>

        <div className="flex items-center gap-2 flex-none">
          <button
            onClick={onBackToChat}
            className="inline-flex items-center gap-1.5 h-9 px-3.5 rounded-lg border border-border bg-white text-[#565656] font-semibold text-xs hover:bg-[#F2EEF5] transition-colors"
          >
            <svg
              width="14"
              height="14"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M19 12H5"></path>
              <path d="m12 19-7-7 7-7"></path>
            </svg>
            Conversation
          </button>
          <button
            onClick={onStartOver}
            className="h-9 px-3.5 rounded-lg border border-border bg-white text-[#565656] font-semibold text-xs hover:bg-[#F2EEF5] transition-colors"
          >
            Start over
          </button>
          <button
            onClick={onDownload}
            disabled={downloading}
            className="inline-flex items-center gap-1.5 h-9 px-3.5 rounded-lg bg-accent hover:brightness-105 text-white font-semibold text-xs disabled:opacity-60 transition"
          >
            <svg
              width="15"
              height="15"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.85"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
              <path d="M7 10l5 5 5-5"></path>
              <path d="M12 15V3"></path>
            </svg>
            {downloading ? "Preparing..." : "Word"}
          </button>
        </div>
      </header>

      <div className="flex-1 flex min-h-0">
        <nav className="w-[220px] flex-none border-r border-border bg-white px-4 py-6 overflow-y-auto hidden md:block">
          <div className="text-[11px] font-bold tracking-wide uppercase text-hint px-2.5 pb-3">
            Contents
          </div>
          {TOC.map((t) => (
            <button
              key={t.id}
              onClick={() => scrollToSection(t.id)}
              className="w-full flex items-center gap-2.5 px-2.5 py-2 rounded-lg text-[13.5px] font-semibold text-[#4A4A4A] hover:bg-accent/8 hover:text-accent transition-colors text-left"
            >
              <span className="font-mono text-[11.5px] font-bold text-hint w-4">{t.num}</span>
              {t.label}
            </button>
          ))}
        </nav>

        <main className="flex-1 overflow-y-auto">
          <div className="max-w-[760px] mx-auto px-6 md:px-10 pb-20">
            <div className="pt-11 pb-8 border-b border-border mb-10">
              <div className="text-[11px] font-bold tracking-[0.09em] uppercase text-accent mb-3.5">
                Software Requirements Specification
              </div>
              <h1 className="font-display font-extrabold text-[32px] tracking-tight text-ink m-0 mb-3.5">
                Requirements Document
              </h1>
              <div className="flex gap-5 text-[12.5px] text-hint font-mono">
                <span>Version 1.0</span>
                <span>Generated by ReqPrint</span>
              </div>
            </div>

            <RequirementsSection requirements={data.requirements} />
            <UserStoriesSection userStories={data.user_stories} />
            <AcceptanceCriteriaSection criteria={data.acceptance_criteria} />
            <UseCasesSection useCases={useCases} />
            <AssumptionsSection assumptions={assumptions} />
          </div>
        </main>

        <div className="hidden lg:block flex-none border-l border-border p-4">
          <RefinePanel
            history={refineHistory}
            onRefine={onRefine}
            loading={refining}
            error={refineError}
          />
        </div>
      </div>

      <div className="lg:hidden border-t border-border p-4">
        <RefinePanel
          history={refineHistory}
          onRefine={onRefine}
          loading={refining}
          error={refineError}
        />
      </div>
    </div>
  );
}
